### ISSUE TITLE
Getting wired underline

### ISSUE THREAD

**Issue by Vakil-Parth** [g0rdan/neon#3]
How to remove this under line?

![Screenshot 2022-02-04 at 5 27 08 PM](https://user-images.githubusercontent.com/46394668/152525306-1e673cf8-e1f9-4172-8417-be5544ee39ea.png)

**Comment by 35C4n0r** [comment]
I'm Having the same issue @g0rdan

**Comment by 35C4n0r** [comment]
I've realised that if the NeonText is used without a MaterialApp Widget the underline appears.

**Comment by dannyfiresnake** [comment]
@35C4n0r -- you need a Scaffold() somewhere in your hierarchy

this is unrelated to neon
